project:
  type: website
 # output-dir:  document

website:
  title: "wendi-white.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: non-science fun.qmd
        text: Non-science fun

format:
  html:
    theme: theme.scss
    backgroundcolor: rgb(89, 98,105)
    fontcolor: black

#editor: visual

